image: docker:19.03.12
services:
  - name: docker:19.03.12-dind

variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:test
    CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:dev
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

stages:
  - build_test
  - release_dev
  - release

before_script:
  - apk update && apk add git
  - git clone --single-branch --branch=develop https://github.com/ergoplatform/ergo-appkit.git
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_test:
  stage: build_test

  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release_dev:
  stage: release_dev
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DEV_IMAGE
    - docker push $CONTAINER_DEV_IMAGE

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:dev -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
